blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/alex2276564/TelegramNotifier#readme
    about: Check out the documentation for installation and configuration guide

  - name: Telegram Bot Father
    url: https://t.me/BotFather
    about: Create your Telegram bot here

  - name: PrestaShop Documentation
    url: https://devdocs.prestashop.com/
    about: Official PrestaShop documentation
