name: Question
description: Ask a question about TelegramNotifier
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Thanks for your interest in TelegramNotifier!"

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about TelegramNotifier?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - "Installation"
        - "Configuration"
        - "Telegram Bot Setup"
        - "Message Templates"
        - "Notifications"
        - "Performance"
        - "Security"
        - "Other"
    validations:
      required: true
